image: registry.gitlab.com/showcheap/android-ci:master

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew
  - sdkmanager "platforms;android-27"
  - sdkmanager "build-tools;27.0.3"

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .gradle/

# TODO: add tests
stages:
 - release

apk:
  stage: release
  script:
    - ./gradlew assembleRelease
    - mv ./app/build/outputs/apk/release/app-release-unsigned.apk ./
  artifacts:
    paths:
      - app-release-unsigned.apk
    name: vplayer-$CI_COMMIT_REF_NAME
